default_layout "default"
copy_command "pbcopy"
copy_clipboard "system"
pane_frames true
mouse_mode true

keybinds {
    normal {
        bind "Alt h" { MoveFocusOrTab "Left"; }
        bind "Alt j" { MoveFocus "Down"; }
        bind "Alt k" { MoveFocus "Up"; }
        bind "Alt l" { MoveFocusOrTab "Right"; }

        bind "Alt H" { MovePane "Left"; }
        bind "Alt J" { MovePane "Down"; }
        bind "Alt K" { MovePane "Up"; }
        bind "Alt L" { MovePane "Right"; }

        bind "Alt b" { NewPane "Right"; }
        bind "Alt v" { NewPane "Down"; }
        bind "Alt Enter" { NewPane "Down"; }
        bind "Alt s" { NewPane "Stacked"; }
        bind "Alt f" { ToggleFocusFullscreen; }
        bind "Alt q" { CloseFocus; }

        bind "Alt 1" { GoToTab 1; }
        bind "Alt 2" { GoToTab 2; }
        bind "Alt 3" { GoToTab 3; }
        bind "Alt 4" { GoToTab 4; }
        bind "Alt 5" { GoToTab 5; }
        bind "Alt 6" { GoToTab 6; }
        bind "Alt 7" { GoToTab 7; }
        bind "Alt 8" { GoToTab 8; }
        bind "Alt 9" { GoToTab 9; }
        bind "Alt 0" { GoToTab 10; }

        bind "Alt r" { SwitchToMode "Resize"; }
    }

    resize {
        bind "h" { Resize "Left"; }
        bind "j" { Resize "Down"; }
        bind "k" { Resize "Up"; }
        bind "l" { Resize "Right"; }
        bind "Esc" "Enter" { SwitchToMode "Normal"; }
    }
}
