;; Cask default config
(source gnu)
(source melpa)


;; Cask dependencies
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")


;; My dependencies
(depends-on "yaml-mode")
(depends-on "web-mode")
(depends-on "virtualenvwrapper")
(depends-on "typescript-mode")
(depends-on "tide")
(depends-on "python-environment")
(depends-on "lua-mode")
(depends-on "jedi")
(depends-on "dired-subtree")
(depends-on "company")

