---
- hosts: localhost
  connection: local
  any_errors_fatal: true
  vars_files:
    - vars.yml
  vars:
    intellij_version: 2017.1.2
    debian_gui_packages:
      - alacarte
      - calibre
      - maven
      - meld
      - vlc
      - xclip
    debian_gui_deb_urls:
      - https://atom.io/download/deb

  tasks:
    - name: install-packages
      become: yes
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ debian_gui_packages }}"
      tags:
        - packages

    - name: install-debs
      become: yes
      apt: deb={{ item }} update-cache=yes
      with_items: "{{ debian_gui_deb_urls }}"

    - name: create-home-opt-dir
      file:
        path: "{{ home_dir }}/{{ home_opt_dir }}"
        state: directory
        mode: 0755

    - name: install-intellij
      unarchive:
        src: "https://download.jetbrains.com/idea/ideaIC-{{ intellij_version }}.tar.gz"
        dest: /home/daniel/{{ home_opt_dir }}
        remote_src: true

    - name: add-spotify-key
      become: yes
      apt_key:
        state: present
        keyserver: "hkp://keyserver.ubuntu.com:80"
        id: "BBEBDCB318AD50EC6865090613B00F1FD2C19886"
      tags:
        - spotify

    - name: add-spotify-repo
      become: yes
      apt_repository:
        state: present
        repo: deb http://repository.spotify.com stable non-free
      tags:
        - spotify

    - name: install-spotify
      become: yes
      apt:
        update-cache: yes
        pkg: spotify-client
      tags:
        - spotify
