---
- hosts: localhost
  connection: local
  any_errors_fatal: true
  vars_files:
    - vars.yml
  vars:
    debian_system_packages:
      - build-essential
      - curl
      - debian-archive-keyring
      - apt-transport-https
      - ffmpeg
      - git
      - git-flow
      - htop
      - jq
      - maven
      - postgresql
      - powertop
      - pwgen
      - tmux
      - uuid-runtime
      - vim
      - silversearcher-ag
      - lynx
      - weechat
      - python-dev
      - python3-dev
    elasticsearch_version: 5.1.11


  tasks:
    - name: Install packages
      become: yes
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ debian_system_packages }}"
      tags:
        - packages

    - name: add-geteventstore-apt-key
      become: yes
      apt_key:
        url: "https://packagecloud.io/EventStore/EventStore-OSS/gpgkey"
        state: present
      tags:
        - geteventstore

    - name: add-geteventstore-repo
      become: yes
      apt_repository:
        repo: deb https://packagecloud.io/EventStore/EventStore-OSS/ubuntu/ xenial main
        state: present
      tags: 
        - geteventstore

    - name: install-geteventstore
      become: yes
      apt:
        update-cache: yes
        pkg: eventstore-oss
      tags: 
        - geteventstore

    - name: add-elasticsearch-apt-key
      become: yes
      apt_key:
        state: present
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      tags:
        - elasticsearch

    - name: add-elasticsearch-repo
      become: yes
      apt_repository:
        state: present
        repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
      tags:
        - elasticsearch

    - name: install-elasticsearch
      become: yes
      apt:
        update-cache: yes
        pkg: elasticsearch
      tags:
        - elasticsearch
    
    - name: add-yarn-apt-key
      become: yes
      apt_key:
        state: present
        url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      tags:
        - yarn

    - name: add-yarn-repo
      become: yes
      apt_repository:
        state: present
        repo: "deb https://dl.yarnpkg.com/debian/ stable main"
      tags:
        - yarn

    - name: install-yarn
      become: yes
      apt:
        update-cache: yes
        pkg: yarn
      tags:
        - yarn

